# Generated by Django 2.0.6 on 2018-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='layout',
            field=models.CharField(choices=[('standard', 'Standard'), ('stacked', 'Stacked')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='nav_color',
            field=models.CharField(default='#001f3f', max_length=8),
        ),
        migrations.AddField(
            model_name='car',
            name='show_nav',
            field=models.BooleanField(default=True),
        ),
    ]
